version: '2'
services:
  neo4j:
    image: 'neo4j'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  backend:
    build: ./
    image: munhunger/indexer
    ports:
      - 8085:8080
    links:
      - neo4j:neo4j
    environment:
      - DB_URL=neo4j
    command: [ "/opt/wait-for-it.sh", "neo4j:7474", "--", "java", "-jar", "/opt/microbundle.jar" ]